# Generated by Django 5.1.7 on 2025-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0002_remove_professor_name_professor_prof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
