# Generated by Django 5.1.7 on 2025-03-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0003_alter_professor_prof_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='prof_id',
            new_name='Name',
        ),
    ]
