# Generated by Django 5.1.7 on 2025-04-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0004_rename_prof_id_professor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNumber', models.IntegerField(blank=True)),
                ('Honors', models.BooleanField(blank=True)),
                ('Subject', models.CharField(blank=True, max_length=4, null=True)),
                ('MeetingDays', models.CharField(blank=True, max_length=50, null=True)),
                ('PassRate', models.FloatField(blank=True)),
            ],
        ),
    ]
