# Generated by Django 5.1.7 on 2025-04-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseNumber',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Honors',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='PassRate',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
