# Generated by Django 5.2 on 2025-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0008_course_endtime_course_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='EndTime',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='StartTime',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
