# Generated by Django 5.1.6 on 2025-02-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='name',
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
