# Generated by Django 5.1.7 on 2025-04-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0006_alter_course_coursenumber_alter_course_honors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='PassRate',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
    ]
