# Generated by Django 5.2 on 2025-04-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0007_alter_course_coursenumber_alter_course_passrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='EndTime',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='StartTime',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
